dependencies:
  config:
    - field.field.node.product.field_product_category
    - field.field.node.product.field_product_property_one
    - field.field.node.product.field_product_property_two
    - field.field.node.product.field_product_related_products
third_party_settings:
  field_group:
    group_product_information:
      children:
        - field_product_category
        - field_product_property_one
        - field_product_property_two
        - field_product_related_products
content:
  field_product_category:
    type: options_select
    weight: 8
    region: content
    settings: {  }
    third_party_settings: {  }
  field_product_property_one:
    type: options_select
    weight: 9
    region: content
    settings: {  }
    third_party_settings: {  }
  field_product_property_two:
    type: options_select
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
  field_product_related_products:
    type: entity_reference_autocomplete
    weight: 11
    region: content
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
