field_settings:
  field_product_category:
    label: Categories
    datasource_id: 'entity:node'
    property_path: field_product_category
    type: integer
    dependencies:
      config:
        - field.storage.node.field_product_category
  field_product_property_one:
    label: 'Property One'
    datasource_id: 'entity:node'
    property_path: field_product_property_one
    type: integer
    dependencies:
      config:
        - field.storage.node.field_product_property_one
  field_product_property_two:
    label: 'Property Two'
    datasource_id: 'entity:node'
    property_path: field_product_property_two
    type: integer
    dependencies:
      config:
        - field.storage.node.field_product_property_two