dependencies:
  config:
    - field.storage.node.field_news_tags
field_settings:
  field_news_tags:
    label: Tags
    datasource_id: 'entity:node'
    property_path: field_news_tags
    type: integer
    dependencies:
      config:
        - field.storage.node.field_news_tags