dependencies:
  config:
    - block.block.news_tags
display:
  news_overview_block:
    display_options:
      header:
        entity_block:
          id: entity_block
          table: views
          field: entity_block
          relationship: none
          group_type: group
          admin_label: ''
          empty: true
          tokenize: false
          target: news_tags
          view_mode: default
          bypass_access: true
          plugin_id: entity
