<?php

/**
 * @file
 * Contains overview_field.module.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\Views;

/**
 * Implements hook_help().
 */
function overview_field_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    // Main module help for the overview_field module.
    case 'help.page.overview_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates a field that loads overviews') . '</p>';
      return $output;

    default:
  }
}

/**
 * Loads a view in the given view mode.
 *
 * @param string $view
 *   The name of the view.
 * @param string $display
 *   The display mode of the view.
 *
 * @return array
 *   Renderable view.
 */
function overview_field_load_view($view, $display) {
  $view = Views::getView($view);
  $content = [];
  if (is_object($view)) {
    $view->setDisplay($display);
    $view->preExecute();
    $view->execute();
    $content = $view->buildRenderable($display);
    $view->postExecute();
  }
  return $content;
}

/**
 * Implements hook_content_export_field_value_alter().
 *
 * Provides support for the single_content_sync module.
 */
function overview_field_content_export_field_value_alter(&$value, FieldItemListInterface $field) {
  switch ($field->getFieldDefinition()->getType()) {
    case 'overview_field':
      $value = $field->getValue();
      break;
  }
}
/**
 * Implements hook_content_import_field_value_alter().
 *
 * Provides support for the single_content_sync module.
 */
function overview_field_content_import_field_value_alter(FieldableEntityInterface $entity, $field_name, $field_value) {
  $field_definition = $entity->getFieldDefinition($field_name);

  switch ($field_definition->getType()) {
    case 'overview_field':
      $entity->set($field_name, $field_value);
      break;
  }
}