dependencies:
  config:
    - field.storage.node.field_blog_tags
field_settings:
  field_blog_tags:
    label: Tags
    datasource_id: 'entity:node'
    property_path: field_blog_tags
    type: integer
    dependencies:
      config:
        - field.storage.node.field_blog_tags