<?php

function _rocketship_job_core_content_migrates() {
  return [
    'djc_images',
    'djc_media_images',
    'djc_text_main_p',
    'djc_nodes',
  ];
}

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_job_core_content_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'rocketship_job_core_content');

  foreach (_rocketship_job_core_content_migrates() as $name) {
    $definitions[$name]['source']['path'] = $path . $definitions[$name]['source']['path'];
  }

  $definitions['djc_images']['source']['constants']['source_base_path'] = $path . $definitions['djc_images']['source']['constants']['source_base_path'];
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after migrate_plus.
 */
function rocketship_job_core_content_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'migration_plugins_alter') {
    $group = $implementations['rocketship_job_core_content'];
    unset($implementations['rocketship_job_core_content']);
    $implementations['rocketship_job_core_content'] = $group;
  }
}