<?php


/**
 * Contains hardcoded list of migrates, for ease of use.
 *
 * @return array
 */
function _rocketship_paragraphs_content_migrates() {
  return [
    'paragraph_images',
    'paragraph_media_images',
    'paragraph_media_videos',
    'p_simple_header',
    'p_001',
    'p_002',
    'p_003',
    'p_014_related_nodes',
    'p_004',
    'p_005',
    'p_006',
    'p_007_child',
    'p_007',
    'p_008',
    'p_009',
    'p_010_child',
    'p_010',
    'p_011',
    'p_014',
    'p_017',
    'paragraph_nodes',
    'para_menu_links',
  ];
}

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_paragraphs_content_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'rocketship_paragraphs_content');

  foreach (_rocketship_paragraphs_content_migrates() as $name) {
    if (!isset($definitions[$name])) {
      continue;
    }
    $definitions[$name]['source']['path'] = $path . $definitions[$name]['source']['path'];
    if ($name === 'paragraph_images') {
      $definitions['paragraph_images']['source']['constants']['source_base_path'] = $path . $definitions['paragraph_images']['source']['constants']['source_base_path'];
    }
  }

}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after migrate_plus.
 */
function rocketship_paragraphs_content_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'migration_plugins_alter') {
    $group = $implementations['rocketship_paragraphs_content'];
    unset($implementations['rocketship_paragraphs_content']);
    $implementations['rocketship_paragraphs_content'] = $group;
  }
}
