rocketship_core.settings:
  type: config_object
  label: 'Rocketship Core settings'
  mapping:
    allow_header_paragraph_on_homepage:
      type: boolean
      label: 'Allow header paragraph on homepage'
block.settings.rocketship_copyright_block:
  type: block_settings
  label: 'Configurable text for block configuration'
  mapping:
    company:
      type: text
      label: 'Company name'
