<?php

/**
 * @file
 * Main module file.
 */

use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Entity\EntityInterface;

define('rocketship_OFFICE_CORE_ANCHOR', 'contact-us');

function _rocketship_office_core_migrates() {
  return [
    'office_core_images',
    'office_core_media_images',
    'office_core_simple_header',
    'office_core_node',
    'office_core_migrate_menu_links',
  ];
}

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_office_core_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'rocketship_office_core');
  $definitions['office_core_images']['source']['path'] = $path . $definitions['office_core_images']['source']['path'];
  $definitions['office_core_media_images']['source']['path'] = $path . $definitions['office_core_media_images']['source']['path'];
  $definitions['office_core_node']['source']['path'] = $path . $definitions['office_core_node']['source']['path'];
  $definitions['office_core_simple_header']['source']['path'] = $path . $definitions['office_core_simple_header']['source']['path'];

  $definitions['office_core_images']['source']['constants']['source_base_path'] = $path . $definitions['office_core_images']['source']['constants']['source_base_path'];
}

/**
 * Implements hook_entity_access().
 */
function rocketship_office_core_webform_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // Restrict access to editing this webform.
  /** @var \Drupal\webform\WebformInterface $entity */
  if (!$account->hasPermission('administer webform') && $entity->id() === 'office_contact' && ($operation === 'update' || $operation === 'delete')) {
    return AccessResult::forbidden('This webform is part of a premade feature and can not be edited or deleted.')
      ->addCacheContexts(['user.permissions']);
  }
}

/**
 * Implements hook_token_info_alter().
 */
function rocketship_office_core_token_info_alter(&$data) {
  $data['tokens']['webform_submission']['site-mail-or-office-override'] = [
    'name' => t('Site email or the email set in the Contact Office where the form is located.'),
    'description' => t('Site email or the email set in the Contact Office where the form is located, if the override is enabled for that Contact Office node.'),
  ];
}

/**
 * Implements hook_tokens().
 */
function rocketship_office_core_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = [];

  if ($type == 'webform_submission' && !empty($data['webform_submission'])) {
    /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
    $webform_submission = $data['webform_submission'];
    $source_entity = $webform_submission->getSourceEntity(TRUE);
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'site-mail-or-office-override':
          $replacements[$original] = \Drupal::config('system.site')
            ->get('mail');
          if ($source_entity && $source_entity->getEntityTypeId() === 'node' && $source_entity->bundle() === 'office') {
            // Do some checks, make sure it's got the right fields, etc.
            // @todo: do tokens need caching or something?
            if (method_exists($source_entity, 'hasField') && $source_entity->hasField('field_office_override_mail') && !empty($source_entity->get('field_office_override_mail')->value)) {
              $replacements[$original] = $source_entity->get('field_office_override_mail')->value;
            }
          }
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_themes_installed().
 *
 * Disable some blocks when one of our themes gets installed and this module
 * is already active at the time.
 */
function rocketship_office_core_themes_installed($theme_list) {
  /** @var \Drupal\Core\Extension\ThemeHandlerInterface $handler */
  $handler = Drupal::service('theme_handler');

  foreach ($theme_list as $theme) {
    $info = $handler->getTheme($theme);
    if (isset($info->info['package']) && $info->info['package'] == 'Rocketship Theme') {
      rocketship_office_core_place_default_blocks($info);
      Rocketship::hideBreadcrumbAndTitleBlockOnContentType($theme, 'office');
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after block_themes_installed.
 */
function rocketship_office_core_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'themes_installed') {
    $group = $implementations['rocketship_office_core'];
    unset($implementations['rocketship_office_core']);
    $implementations['rocketship_office_core'] = $group;
  }
  if ($hook == 'migration_plugins_alter') {
    $group = $implementations['rocketship_office_core'];
    unset($implementations['rocketship_office_core']);
    $implementations['rocketship_office_core'] = $group;
  }
}

/**
 * Place our blocks in a doormat region of the provided theme.
 *
 * @param \Drupal\Core\Extension\Extension $theme
 *   Theme name.
 */
function rocketship_office_core_place_default_blocks($theme) {
  $regions = $theme->info['regions'];
  if (isset($regions['doormat_04'])) {
    $region = 'doormat_04';
  }
  elseif (isset($regions['doormat'])) {
    $region = 'doormat';
  }
  else {
    $region = array_key_last($regions);
  }

  Rocketship::placeBlock('views_block:footer_offices-footer', [
      'region' => $region,
      'theme' => $theme->getName(),
      'label' => 'Contact',
      'provider' => 'views',
      'label_display' => 'visible',
      'views_label' => 'Contact',
      'items_per_page' => 0,
    ]
  );
}

/**
 * Implements hook_form_alter().
 */
function rocketship_office_core_form_webform_submission_office_contact_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $form['scroll_to'] = [
    // Fingers crossed nobody puts two of these on the same page.
    // Can't use Unique ID method cuz this alter gets called twice per request.
    '#markup' => '<div id="' . rocketship_OFFICE_CORE_ANCHOR . '" class="scroll-to-anchor"></div>',
    '#weight' => -9999,
  ];

}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Change the text for Promoted to front & hide sticky if
 * advanced isn't enabled.
 */
function rocketship_office_core_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();

  if ($node->bundle() !== 'office') {
    return;
  }

  $form['promote']['widget']['value']['#title'] = t('Show this office in the footer of your site');
  $form['options']['#open'] = TRUE;
  if (!\Drupal::moduleHandler()->moduleExists('rocketship_office_advanced')) {
    // No use for sticky until Advanced is enabled.
    $form['sticky']['#access'] = FALSE;
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function rocketship_office_core_menu_local_tasks_alter(&$local_tasks) {
  if (isset($local_tasks['tabs'][0]['webform_view:webform_views:view.doffice_contact_submissions.application_page'])) {
    // Only show Submissions link on Office nodes.
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node && is_string($node)) {
      $node = Node::load($node);
    }
    if ($node instanceof NodeInterface && $node->bundle() !== 'office') {
      unset($local_tasks['tabs'][0]['webform_view:webform_views:view.doffice_contact_submissions.application_page']);
    }
  }
  if (isset($local_tasks['tabs'][0]['views_view:view.doffice_contact_submissions.application_page'])) {
    // Only show Submissions link on Office nodes.
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node && is_string($node)) {
      $node = Node::load($node);
    }
    if ($node instanceof NodeInterface && $node->bundle() !== 'office') {
      unset($local_tasks['tabs'][0]['views_view:view.doffice_contact_submissions.application_page']);
    }
  }
}

/**
 * Implements hook_theming_page_attachments().
 */
function rocketship_office_core_page_attachments(array &$attachments) {

  // Make the form settings available in the javascript, twig, … because we
  // need some of them to selectively add HTML classes or JS functions.
  $config = \Drupal::config('rocketship_office_core.settings');
  $cssStructural = $config->get('css_structural');

  $variables['#attached']['drupalSettings']['rocketship_office_core']['css_structural'] = $cssStructural;

  // Check the form settings to see if we need to attach certain libs, we only
  // load critical CSS library in front theme, not admin.
  if (\Drupal::service('router.admin_context')->isAdminRoute() == FALSE) {

    // Only if structural css is chosen.
    if ($cssStructural) {
      $attachments['#attached']['library'][] = 'rocketship_office_core/structural';
    }
  }
}
