field_settings:
  rendered_item_search_index:
    configuration:
      view_mode:
        'entity:node':
          event: search_index
  event_last_end_date:
    label: 'Event: last end date'
    property_path: aggregated_field
    type: date
    configuration:
      type: max
      fields:
      - 'entity:node/field_events:entity:date_end'
  event_first_start_date:
    label: 'Event: first start date'
    property_path: aggregated_field
    type: date
    configuration:
      type: min
      fields:
      - 'entity:node/field_events:entity:date_start'
  date_end:
    label: 'Events » Event » Event end'
    datasource_id: 'entity:node'
    property_path: 'field_events:entity:date_end'
    type: date
    dependencies:
      config:
      - field.storage.node.field_events
      module:
      - rocketship_event_core
  date_start:
    label: 'Events » Event » Event start'
    datasource_id: 'entity:node'
    property_path: 'field_events:entity:date_start'
    type: date
    dependencies:
      config:
      - field.storage.node.field_events
      module:
      - rocketship_event_core