field_settings:
  field_job_property_one:
    label: Job Property One
    datasource_id: 'entity:node'
    property_path: field_job_property_one
    type: integer
    dependencies:
      config:
        - field.storage.node.field_job_property_one
  field_job_category:
    label: 'Job Category'
    datasource_id: 'entity:node'
    property_path: field_job_category
    type: integer
    dependencies:
      config:
        - field.storage.node.field_job_category
  field_job_property_two:
    label: 'Job Property Two'
    datasource_id: 'entity:node'
    property_path: field_job_property_two
    type: integer
    dependencies:
      config:
        - field.storage.node.field_job_property_two
