display:
  job_overview_block:
    display_options:
      header:
        area:
          id: area
          table: views
          field: area
          relationship: none
          group_type: group
          admin_label: ''
          empty: true
          tokenize: false
          content:
            value: "<h3>To rename the filters:</h3>\r\n\r\n<p>Rename the 3 taxonomies and change their rabbit hole settings. Rename the Facets themselves. Change the URL alias in the facets. Make sure they match the Rabbit hole settings.</p>\r\n\r\n<h3>To add the Facet filters to this page:</h3>\r\n<p>Edit this page, specifically the Overview paragraph, and select all Facets and blocks you want to add to this view</p>\r\n<p>Don't forget to add the \"Search redirect block\"</p>\r\n\r\n<h3>To create new Facet filters:</h3>\r\n<ul>\r\n\t<li>Add new vocabulary</li>\r\n\t<li>Add reference field to this content type</li>\r\n\t<li>Add that reference field to the content index (search api)</li>\r\n\t<li>Set up the facet for the new vocabulary - Select \"List of links for the Jobs feature\"</li>\r\n        <li>Follow the same steps as above to add it to this page</li>\r\n</ul>\r\n<p>&nbsp;</p>"
            format: full_html
          plugin_id: text
        result:
          id: result
          table: views
          field: result
          relationship: none
          group_type: group
          admin_label: ''
          empty: false
          content: 'Showing @start-@end of @total jobs'
          plugin_id: result