<?php

/**
 * @file
 * Main module file.
 */

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function rocketship_news_basic_overview_field_options_alter(array &$options) {
  $options['news_overview'] = t('Show a list of news articles on your website');
  $options['news_overview_front'] = t('Show the last three promoted news articles');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function rocketship_news_basic_overview_field_output_alter($key, array &$output) {
  if ($key == 'news_overview') {
    $output = overview_field_load_view('news_overview', 'news_overview_block');
  }
  if ($key == 'news_overview_front') {
    $output = overview_field_load_view('news_overview', 'news_overview_front');
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_news_basic_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'rocketship_news_basic');
  $definitions['rocketship_news_overview']['source']['path'] = $path . $definitions['rocketship_news_overview']['source']['path'];
  $definitions['rocketship_news_overview_header']['source']['path'] = $path . $definitions['rocketship_news_overview_header']['source']['path'];
  $definitions['rocketship_news_overview_p']['source']['path'] = $path . $definitions['rocketship_news_overview_p']['source']['path'];
  $definitions['rocketship_news_blocks']['source']['path'] = $path . $definitions['rocketship_news_blocks']['source']['path'];
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after migration_plus.
 */
function rocketship_news_basic_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'migration_plugins_alter') {
    $group = $implementations['rocketship_news_basic'];
    unset($implementations['rocketship_news_basic']);
    $implementations['rocketship_news_basic'] = $group;
  }
}
