<?php


function _rocketship_realisation_core_content_migrates() {
  return [
    'drc_images',
    'drc_media_images',
    'drc_text_main_p',
    'drc_nodes',
  ];
}

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_realisation_core_content_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'rocketship_realisation_core_content');

  foreach (_rocketship_realisation_core_content_migrates() as $name) {
    $definitions[$name]['source']['path'] = $path . $definitions[$name]['source']['path'];
  }

  $definitions['drc_images']['source']['constants']['source_base_path'] = $path . $definitions['drc_images']['source']['constants']['source_base_path'];
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after migrate_plus.
 */
function rocketship_realisation_core_content_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'migration_plugins_alter') {
    $group = $implementations['rocketship_realisation_core_content'];
    unset($implementations['rocketship_realisation_core_content']);
    $implementations['rocketship_realisation_core_content'] = $group;
  }
}