<?php

/**
 * @file
 * Main module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_office_advanced_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'rocketship_office_advanced');
  $definitions['rocketship_office_overview']['source']['path'] = $path . $definitions['rocketship_office_overview']['source']['path'];
  $definitions['rocketship_office_overview_header']['source']['path'] = $path . $definitions['rocketship_office_overview_header']['source']['path'];
  $definitions['rocketship_office_overview_p']['source']['path'] = $path . $definitions['rocketship_office_overview_p']['source']['path'];
}

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function rocketship_office_advanced_overview_field_options_alter(array &$options) {
  $options['office_overview_main_offices'] = t('Show all contact offices that are marked as "Main offices". See promotion options for Contact Office.');
  $options['office_overview_offices_map'] = t('Show all contact offices on a google map. Includes main and satellite offices.');
  $options['office_overview_satellite_offices'] = t('Show all satellite Contact Offices in teaser view modes.');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function rocketship_office_advanced_overview_field_output_alter($key, array &$output) {
  if ($key == 'office_overview_main_offices') {
    $output = overview_field_load_view('office_overview', 'main_offices');
  }
  if ($key == 'office_overview_offices_map') {
    $output = overview_field_load_view('office_overview', 'offices_map');
  }
  if ($key == 'office_overview_satellite_offices') {
    $output = overview_field_load_view('office_overview', 'satellite_offices');
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Change the text for sticky option.
 */
function rocketship_office_advanced_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();

  if ($node->bundle() !== 'office') {
    return;
  }

  $form['sticky']['widget']['value']['#title'] = t('Show this office as the main contact office on the Contact Offices landingspage.');

  $uuid = '69352ecf-1e01-49fb-a7b6-a8490803a9da';
  $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['uuid' => $uuid]);
  if ($nodes) {
    $overview = reset($nodes);
    $form['sticky']['widget']['value']['#title'] = t('Show this office as the main office on the @title page.', ['@title' => $overview->label()]);
  }
}
