<?php

/**
 * @file
 * Main module file.
 */

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function rocketship_job_basic_overview_field_options_alter(array &$options) {
  $options['job_overview'] = t('Show a list of job articles on your website');
  $options['job_overview_front'] = t('Show the last three promoted job articles');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function rocketship_job_basic_overview_field_output_alter($key, array &$output) {
  if ($key == 'job_overview') {
    $output = overview_field_load_view('job_overview', 'job_overview_block');
  }
  if ($key == 'job_overview_front') {
    $output = overview_field_load_view('job_overview', 'job_overview_front');
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_job_basic_migration_plugins_alter(&$definitions) {
  if (!isset($definitions['rocketship_job_overview'])) {
    return;
  }
  $path = drupal_get_path('module', 'rocketship_job_basic');
  $definitions['rocketship_job_overview']['source']['path'] = $path . $definitions['rocketship_job_overview']['source']['path'];
  $definitions['rocketship_job_overview_header']['source']['path'] = $path . $definitions['rocketship_job_overview_header']['source']['path'];
  $definitions['rocketship_job_overview_p']['source']['path'] = $path . $definitions['rocketship_job_overview_p']['source']['path'];
}
