<?php

/**
 * @file
 * The main module file.
 */

use Drupal\Core\Cache\Cache;

/**
 * Adds an option to the overview field.
 *
 * @param array $options
 *   Contains all the options for the overview field.
 */
function rocketship_service_basic_overview_field_options_alter(array &$options) {
  $options['service_overview'] = t('Show a list of service articles on your website');
  $options['service_overview_front'] = t('Show a limited list of promoted service articles for your front page');
}

/**
 * Defines what should be returned in the overview.
 *
 * @param string $key
 *   The key defined in hook_overview_options_alter().
 * @param array $output
 *   A renderable array of data, that needs to be displayed in the field.
 */
function rocketship_service_basic_overview_field_output_alter($key, array &$output) {
  if ($key == 'service_overview') {
    $output = overview_field_load_view('service_overview', 'service_overview_block');
  }
  if ($key == 'service_overview_front') {
    $output = overview_field_load_view('service_overview', 'service_overview_front');
    // Cache this one, speed up homepage a bit for webadmin.
    $output['#cache']['max-age'] = Cache::PERMANENT;
    $output['#cache']['tags'][] = 'node_list';
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_service_basic_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'rocketship_service_basic');
  $definitions['rocketship_service_overview']['source']['path'] = $path . $definitions['rocketship_service_overview']['source']['path'];
  $definitions['rocketship_service_overview_header']['source']['path'] = $path . $definitions['rocketship_service_overview_header']['source']['path'];
  $definitions['rocketship_service_overview_p']['source']['path'] = $path . $definitions['rocketship_service_overview_p']['source']['path'];
  $definitions['rocketship_service_blocks']['source']['path'] = $path . $definitions['rocketship_service_blocks']['source']['path'];
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after migration_plus.
 */
function rocketship_service_basic_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'migration_plugins_alter') {
    $group = $implementations['rocketship_service_basic'];
    unset($implementations['rocketship_service_basic']);
    $implementations['rocketship_service_basic'] = $group;
  }
}
