<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_theme().
 */
function rocketship_product_advanced_theme($existing, $type, $theme, $path) {
  return [
    'product_facets_result_item' => [
      'base hook' => 'facets_result_item',
      'variables' => [
        'facet' => NULL,
        'raw_value' => '',
        'value' => '',
        'show_count' => FALSE,
        'count' => NULL,
        'is_active' => FALSE,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function rocketship_product_advanced_page_attachments(array &$attachments) {

  // Get our library from the discovery list.
  $module_library = \Drupal::service('library.discovery')
    ->getLibraryByName('rocketship_product_advanced', 'f009');

  // If our library exists, attach it.
  if (isset($module_library)) {
    $attachments['#attached']['library'][] = 'rocketship_product_advanced/f009';
  }
}
