name: 'Dropsolid Rocketship Demo Config'
type: module
description: 'Contains configuration to specifically set up a Demo Site'
core_version_requirement: ^8.8 || ^9
package: Rocketship
group: 'Demo Site'
weight: 30
show_during_install: true
dependencies:
  - blazy
  - block_content
  - config_rewrite
  - content_translation
  - rocketship_blocks
  - field
  - language
  - link
  - media
  - media_library
  - migrate_plus
  - rocketship_content
  - rocketship_core
  - rocketship_paragraphs
  - text

# Information added by Drupal.org packaging script on 2021-11-08
version: '5.0.0-beta7'
project: 'dropsolid_rocketship_profile'
datestamp: 1636363213
